[package]
name = "dns_benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
rand = "0.9.2"
clap = { version = "4.5.54", features = ["derive"] }
anyhow = "1.0.100"
bytes = "1.11.0"
futures = "0.3.31"
indicatif = "0.18.3"
